### ISSUE TITLE
observable-slim throwing error on IE11 proxy is undefined with babel

### ISSUE THREAD

**Issue by akashishu777** [ElliotNB/observable-slim#40]
Is there any way we can enable observable-slim to use proxy from polyfill?

https://babeljs.io/docs/en/learn#proxies

**Comment by ElliotNB** [comment]
@akashishu777 Yes, but you have to use the `Proxy` polyfill provided in this repo. Please see the `proxy.js` and `proxy.min.js` files located in the base directory of the repo. They are forked from the official `Proxy` polyfill maintained by GoogleChrome ( https://github.com/GoogleChrome/proxy-polyfill ). I've modified the `Proxy` polyfill to intercept `Array` mutation methods so that operations like `slice` `splice` `pop` and so on can be observed in IE11.

Would it be helpful if I published the forked `Proxy` polyfill on npm?

**Comment by akashishu777** [comment]
Hi @ElliotNB, Thanks a lot for your work, there is no need to publish the forked Proxy polyfill, You can close this ticket now. Thanks!
